### PR TITLE
Better names for type members

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by laughedelic** [comment]
> Cat -> Category

 why so long? I was going to suggest renaming `Objects` to `Obj` (or at least to use singular form)

**Comment by eparejatobes** [comment]
I've become a bit hostile to shortenings. This way you don't need to think much when using it somewhere else.

**Comment by laughedelic** [comment]
Ok. But what about more consistency in singular vs. plural?

**Comment by eparejatobes** [comment]
@laughedelic where?

**Comment by laughedelic** [comment]
- `AnyCategory#Objects`
- `AnyProducts`
- `AnyCoproducts`

What I think is a bit confusing with plurals is when you say `X <: C#Objects`, it reads as if `X` was a set of objects, not _an_ object.
With (co)products it's probably different, but then why some structures became "categories" and others somethings else?

**Comment by eparejatobes** [comment]
Well `Objects` is plural because it acts as a 2-type in a way: *subtypes* of that type are objects. About (co)products I think that (co)cartesian monoidal category is a bit too much.

**Comment by laughedelic** [comment]
> it acts as a 2-type in a way: subtypes of that type are objects

so why does it have to be plural? I understand what you're saying, but I don't see the logic

**Comment by laughedelic** [comment]
merging anyway

**Pull request merged**
