### PR TITLE
Set up Travis and Codacy

### PR DESCRIPTION
**Pull request by laughedelic**

### CODE REVIEW

**Comment by laughedelic** [comment]
@eparejatobes I'm note sure how to setup codacy coverage. I see an API key on Codacy, but how do I relate it with Travis?

**Comment by eparejatobes** [comment]
I did it in cosas, it's a bit funny. I no longer remember how it was supposed to be done.

**Comment by eparejatobes** [comment]
see this: https://github.com/ohnosequences/cosas/blob/master/.travis.yml#L7-L10

**Comment by laughedelic** [comment]
For reference: it requires setting up travis CLI and running `travis encrypt CODACY_PROJECT_TOKEN=...`

**Pull request merged**
